CREATE TABLE books (
  book_id integer PRIMARY KEY generated by default AS identity,
  title varchar(255),
  publication_year integer,
  in_stock boolean default true,
  author_id integer references authors(author_id)
);